import type { CSSProperties } from "react";

export const s = {
  page: { padding: "28px 32px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 4 } satisfies CSSProperties,
  heading: { fontSize: 26, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  repoName: { color: "var(--accent)", fontWeight: 700 } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginBottom: 20,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  progress: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    marginBottom: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  error: {
    padding: "12px 14px",
    marginBottom: 16,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 13,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  summary: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 16,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  created: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 16,
    borderRadius: 8,
    border: "1px solid var(--ok)",
    background: "var(--bg-surface)",
    fontSize: 13,
  } satisfies CSSProperties,
  createdLink: { color: "var(--accent)", fontWeight: 600 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  bar: {
    position: "sticky",
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 20,
    padding: "12px 16px",
    borderRadius: 10,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    boxShadow: "var(--shadow-modal)",
    fontSize: 13,
  } satisfies CSSProperties,
};
