import type { CSSProperties } from "react";

export const s = {
  loadingStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  panel: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    columnGap: 16,
    rowGap: 14,
    alignItems: "start",
    padding: "18px 20px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  badgeCol: { paddingTop: 2 } satisfies CSSProperties,
  body: {
    gridColumn: "2",
    minWidth: 0,
    paddingRight: 28,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  title: {
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 1.4,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  description: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  refresh: {
    position: "absolute",
    top: 14,
    right: 16,
    display: "inline-flex",
    padding: 4,
    background: "none",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footer: {
    gridColumn: "1 / -1",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  footerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  } satisfies CSSProperties,
  footerRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginLeft: "auto",
  } satisfies CSSProperties,
  footerNote: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  detailsToggle: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    font: "inherit",
    fontSize: 12,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  details: {
    gridColumn: "1 / -1",
    borderTop: "1px solid var(--border)",
    paddingTop: 16,
  } satisfies CSSProperties,
  block: {
    marginBottom: 18,
  } satisfies CSSProperties,
  blockLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  prose: {
    fontSize: 14,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  riskList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  riskHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "10px 12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    font: "inherit",
    color: "inherit",
  } satisfies CSSProperties,
  sevDot: (color: string) =>
    ({
      width: 8,
      height: 8,
      borderRadius: 99,
      background: color,
      flexShrink: 0,
    }) satisfies CSSProperties,
  sevLabel: (color: string) =>
    ({
      fontSize: 11,
      fontWeight: 700,
      color,
      flexShrink: 0,
    }) satisfies CSSProperties,
  kindLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  riskTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 13.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  chevron: (open: boolean) =>
    ({
      flexShrink: 0,
      transform: open ? "rotate(180deg)" : "none",
      transition: "transform 0.15s ease",
      color: "var(--text-muted)",
    }) satisfies CSSProperties,
  riskBody: {
    padding: "0 12px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  refRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  } satisfies CSSProperties,
  focusList: {
    listStyle: "decimal",
    margin: 0,
    paddingLeft: 20,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  focusItem: {
    fontSize: 13.5,
  } satisfies CSSProperties,
  focusButton: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    font: "inherit",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  focusReason: {
    color: "var(--text-secondary)",
    marginLeft: 6,
  } satisfies CSSProperties,
} as const;
