import type { CSSProperties } from "react";

/** Co-located styles for SkillConfigTab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", marginBottom: 20 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  enabledLabel: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 14px",
    marginBottom: 20,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--warn-bg)",
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  noticeIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 10, marginTop: 10 } satisfies CSSProperties,
  savedNote: { fontSize: 13, color: "var(--ok)" } satisfies CSSProperties,
  matches: {
    marginBottom: 20,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  matchesTitle: { fontSize: 13, fontWeight: 700, color: "var(--crit)" } satisfies CSSProperties,
  matchesHint: { fontSize: 12.5, color: "var(--text-secondary)", margin: "4px 0 10px" } satisfies CSSProperties,
  matchList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  matchItem: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  matchMeta: { display: "flex", alignItems: "center", gap: 10, fontSize: 12 } satisfies CSSProperties,
  matchRule: { fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  matchSeverity: (severity: "high" | "medium"): CSSProperties => ({
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: severity === "high" ? "var(--crit)" : "var(--warn)",
  }),
  matchLine: { color: "var(--text-muted)" } satisfies CSSProperties,
  matchExcerpt: {
    padding: "4px 8px",
    borderRadius: 4,
    background: "var(--bg-primary)",
    color: "var(--text-secondary)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
} as const;
